seed: 42

model: resnet50
pretrained: true

data_root: /home/blue_lobster/Downloads/birds_of_california/data

image_size: 224
batch_size: 8

epochs: 2
learning_rate: 1e-4

val_split: 0.1
num_workers: 2
use_amp: true
prefetch_factor: 2
compile_model: false
cudnn_benchmark: true
float32_matmul_precision: high
clear_logs_before_run: true

max_samples: 500
log_interval: 5

output_dir: /home/blue_lobster/PycharmProjects/Model_California_Birds/outputs
