seed: 42

model: resnet50
pretrained: true

data_root: /Users/wangyiding/ML_Model_CaliforniaBirds/data

image_size: 224
batch_size: 32

epochs: 20
learning_rate: 0.0003

val_split: 0.1
num_workers: 0

log_interval: 50

output_dir: /Users/wangyiding/ML_Model_CaliforniaBirds/outputs